In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)

scores = np.random.randint(0,101,(4,3))
print(scores)

players = ['Virat','Rohit','MS Dhoni','Hardik Pandya']      #index
matches = ['Match 1','Match 2','Match 3',]                  #column

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [ ]:
df = pd.DataFrame(data=scores)
print(df)
df = pd.DataFrame(data=scores, index=players)
print(df)
df = pd.DataFrame(data=scores, index=players, columns=matches)
print(df)


    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63
                0   1   2
Virat          95  11  81
Rohit          70  63  87
MS Dhoni       75   9  77
Hardik Pandya  40   4  63
               Match 1  Match 2  Match 3
Virat               95       11       81
Rohit               70       63       87
MS Dhoni            75        9       77
Hardik Pandya       40        4       63


LOC and ILOC (Indexers, not Functions)

LOC- using numeric index

ILOC- cannot use numeric index, have to use labelled index

Generally we dont see Loc being used, but Iloc we do

In [ ]:
print(df)
print(df.info())

print(df.loc['Virat'])              #Row Virat
print(df.loc[['Virat','Rohit']])    #Multiple rows
print(df.loc['Virat','Match 2'])    #Specific cell
print(df.loc[['Virat','MS Dhoni'],['Match 1','Match 3']])   #Subset of Rows and columns

               Match 1  Match 2  Match 3
Virat               95       11       81
Rohit               70       63       87
MS Dhoni            75        9       77
Hardik Pandya       40        4       63
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Virat to Hardik Pandya
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Match 1  4 non-null      int32
 1   Match 2  4 non-null      int32
 2   Match 3  4 non-null      int32
dtypes: int32(3)
memory usage: 252.0+ bytes
None
Match 1    95
Match 2    11
Match 3    81
Name: Virat, dtype: int32
       Match 1  Match 2  Match 3
Virat       95       11       81
Rohit       70       63       87
11


In [8]:
print(df.iloc[0])       #First row
print(df.iloc[0:2])     #First two rows
print(df.iloc[0,1])     #First row, second column
print(df.iloc[[0,2],[0,2]])     #Rows 0 & 2, columns 0 & 2

Match 1    95
Match 2    11
Match 3    81
Name: Virat, dtype: int32
       Match 1  Match 2  Match 3
Virat       95       11       81
Rohit       70       63       87
11
          Match 1  Match 3
Virat          95       81
MS Dhoni       75       77
