In [25]:
import numpy as np

#Creating 1d and 2d array and printing result


In [26]:
#1D Array
virat_runs = np.array([45, 70, 34, 89, 23])
print(virat_runs)

[45 70 34 89 23]


In [27]:
#2D Array
team_runs = np.array([
    [45, 70, 34, 89, 23],
    [56, 78, 90, 12, 67],
    [67, 89, 45, 23, 78]
])
print(team_runs)

[[45 70 34 89 23]
 [56 78 90 12 67]
 [67 89 45 23 78]]


Creating 1d array from tuple 

In [28]:
#1D array from a tuple - Player ages
player_ages = np.array((28, 30, 25, 32, 27))
print(player_ages)

[28 30 25 32 27]


These are special kinds of arrays like full or zeros, ones, eyes

In [29]:
#special arrays 
zeros = np.zeros((3, 4))  # 3x4 array of zeros
ones = np.ones((2, 5))    # 2x5 array of ones
identity = np.eye(4)      # 4x4 identity matrix
print(zeros)
print(ones)

empty = np.empty((2, 3))  # 2x3 empty array
full = np.full((3, 3), 7)  # 3x3 array filled with 7
print(empty)
print(full)
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[43.59411816 39.24589744 43.88953097]
 [48.58564685 29.55708778 36.57475133]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Creating arrays with range

In [30]:
arr = np.arange (55,65) 
print(arr,arr[0],arr[5],arr[9])
arr[4]=69
print("\n", arr[4])

[55 56 57 58 59 60 61 62 63 64] 55 60 64

 69


Runrates (run/over)
Values from 4 upto 11, step= 1
start=4, stop=11(excluded),step=1
values increase by 1 each time->evenly space , but step is fixed manually

In [31]:
run_rates= np.arange(4,11,2)
print(run_rates)

[ 4  6  8 10]


Arange vs Linspace function
- Arange exludes upper end while linspace includes.
- (_,_,x) x is step in arange (How many elements we want to skip)
- (_,_,x) produces x evenly spaced values in Linspace(How many elements we want)

In [32]:
a = np.arange(1,10,3)
l = np.linspace(1,10,3)
lb = np.linspace(1,10,6, dtype=int)
print(a, l, lb)

[1 4 7] [ 1.   5.5 10. ] [ 1  2  4  6  8 10]


Random numbers

generates n random numbers uniformly between a and b

lower =100,

upper limit =200,

how many elements do you want=10 


In [33]:
strike_rates= np.random.uniform(100,200,10)
print(strike_rates)

[179.56783022 199.569585   189.0012144  115.96015716 100.22066281
 182.74809457 149.87731685 182.43708654 182.73497841 182.91726052]


Creating 2d array
...

In [34]:
batting_avg= np.random.normal(40,5,(2,3))
print(batting_avg)

[[42.17842008 41.90458449 39.59512679]
 [41.40545157 31.67974264 39.08142144]]
