   We cannot append an array, once its made.
   To do that we have to create a new array.

In [17]:
import numpy as np
arr = np.arange(0,10)
new_arr_single = np.append(arr, 10)
new_arr_multiple = np.append(arr, [10,11,12])
print(arr)
print(new_arr_single)
print(new_arr_multiple)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


#Shallow copy: Suppose we have array a, then we do b =a[0:5]

-> b will not have serparate memory, instead b will point to the array a

b->a->memory

#Deep copy: Suppose we have array a, then we do b=a.copy()
-> b will have separate memory, not a's memory

b->memory   a->memory

if we change b, it will not impact a ... and vice-versa

In [18]:
marks=np.array([55,26,25,42,55,57,44,55,45,45])

In [19]:
print (marks)

[55 26 25 42 55 57 44 55 45 45]


Indexing

In [20]:
print(marks[8])

45


Slicing
View or Shallow copy

In [21]:
print(marks[1:4])

[26 25 42]


Modifying slice

Deep copy (affects the original)

In [22]:
top_batch[:]=99
print(top_batch)
print(marks)

[ True  True  True  True  True  True  True  True  True  True]
[55 26 25 42 55 57 44 55 45 45]


To avoid this, use copy()

In [23]:
#broadcasting
print(marks[:6])

[55 26 25 42 55 57]


vectorization

In [24]:
result=marks+100
print(result)

[155 126 125 142 155 157 144 155 145 145]


In [25]:
top_batch=marks>35
print(top_batch)

[ True False False  True  True  True  True  True  True  True]


Conditional Selection

In [27]:
marks = np.array([69,26,78,91,53,34])
print(marks)

passed =  marks >= 35 #boolean array
print(passed)
print(marks[passed])

[69 26 78 91 53 34]
[ True False  True  True  True False]
[69 78 91 53]


In [28]:
print(marks[passed==False])

[26 34]


In [30]:
#or directly:
print(marks[marks>35])

[69 78 91 53]
