Numpy Operations

In [3]:
import numpy as np

In [5]:
arr = np.arange(0,10)

In [7]:
#Basic arithmatics
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr / arr)
print(arr ** 3)
print(np.sqrt(arr))


[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  0   1   8  27  64 125 216 343 512 729]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_7600\942044383.py:5: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)


In [8]:
#Summary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())    #variance
print(arr.std())    #standard deviation

45
4.5
9
0
8.25
2.8722813232690143


In [9]:
#Reversing an array
arr = np.array([1,2,3,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [11]:
#Sorting an array
arr = np.array([5,2,8,1,3])
sorted_arr = np.sort(arr)
print(sorted_arr)

#For descending
#there is no option of descending in numpy sir!!! please use pandas!!
sorted_arr = np.sort(arr)[::-1]     #Reverse the party
print(sorted_arr)

[1 2 3 5 8]
[8 5 3 2 1]
